# Generated by Django 6.0.1 on 2026-01-31 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(default='未知', max_length=100, verbose_name='作者')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('content', models.TextField(verbose_name='章节内容')),
                ('index', models.IntegerField(default=0, verbose_name='排序索引')),
                ('volume_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='分卷名称')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='reader.book', verbose_name='所属书籍')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.book', verbose_name='书籍')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.chapter', verbose_name='当前章节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '阅读进度',
                'verbose_name_plural': '阅读进度',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
