# Generated by Django 6.0.1 on 2026-02-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_bookshelf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['book', 'index'], 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
    ]
