# Generated by Django 6.0.1 on 2026-02-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_alter_chapter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='illustrations/', verbose_name='插图')),
                ('index', models.IntegerField(default=0, verbose_name='排序索引')),
                ('volume_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='分卷名称')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='reader.book', verbose_name='所属书籍')),
            ],
            options={
                'verbose_name': '插图',
                'verbose_name_plural': '插图',
                'ordering': ['book', 'index'],
            },
        ),
    ]
