# Generated by Django 6.0.1 on 2026-02-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_illustration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_mode', models.CharField(choices=[('open', '完全开放注册'), ('invite', '仅凭邀请码注册'), ('closed', '关闭注册')], default='open', max_length=10, verbose_name='注册模式')),
                ('invite_code', models.CharField(blank=True, default='888888', max_length=50, verbose_name='邀请码 (仅在邀请模式下有效)')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
    ]
