# Generated by Django 6.0.1 on 2026-02-12 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_book_uploader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='积分')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='经验值')),
                ('last_checkin_time', models.DateTimeField(verbose_name='上次签到时间')),
                ('user_level', models.CharField(choices=[('LV0', '普通用户'), ('LV1', '黑铁会员'), ('LV2', '青铜会员'), ('LV3', '白银会员'), ('LV4', '黄金会员'), ('LV5', '铂金会员'), ('LV6', '钻石会员')], default='LV0', max_length=10, verbose_name='会员等级')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户积分',
                'verbose_name_plural': '用户积分',
            },
        ),
    ]
