# Generated by Django 6.0.1 on 2026-02-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_userpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoints',
            name='last_checkin_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上次签到时间'),
        ),
    ]
