# Generated by Django 6.0.1 on 2026-02-12 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_alter_userpoints_last_checkin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoints',
            name='last_checkin_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上次签到时间'),
        ),
    ]
