# Generated by Django 6.0.1 on 2026-02-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_alter_userpoints_last_checkin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='word_count',
            field=models.PositiveIntegerField(default=0, verbose_name='总字数'),
        ),
    ]
