# Generated by Django 6.0.1 on 2026-02-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0011_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': '小说', 'verbose_name_plural': '小说'},
        ),
        migrations.AddField(
            model_name='book',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
    ]
