# Generated by Django 6.0.1 on 2026-02-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0012_alter_book_options_book_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='illustration_count',
            field=models.PositiveIntegerField(default=0, verbose_name='插图数量'),
        ),
    ]
