# Generated by Django 6.0.1 on 2026-02-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0013_book_illustration_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='收录时间'),
        ),
    ]
