# Generated by Django 6.0.3 on 2026-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0014_alter_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='标签'),
        ),
    ]
