# Generated by Django 6.0.1 on 2026-03-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0016_tag_remove_book_tags_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='recos',
            field=models.PositiveIntegerField(default=0, verbose_name='Reco数'),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='reco_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Recos'),
        ),
    ]
