# Generated by Django 6.0.1 on 2026-03-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0017_book_recos_userpoints_reco_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at', '-recos'], 'verbose_name': '小说', 'verbose_name_plural': '小说'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_recommended',
        ),
    ]
