# Generated by Django 6.0.1 on 2026-03-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0017_staffapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at', '-recos'], 'verbose_name': '小说', 'verbose_name_plural': '小说'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_recommended',
        ),
        migrations.AddField(
            model_name='book',
            name='recos',
            field=models.PositiveIntegerField(default=0, verbose_name='Reco数'),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='reco_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Recos'),
        ),
    ]
