# Generated by Django 6.0.1 on 2026-03-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0018_alter_book_options_remove_book_is_recommended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpoints',
            name='user_level',
        ),
    ]
