# Generated by Django 6.0.1 on 2026-04-04 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0019_remove_userpoints_user_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='当日已投推荐数')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.book', verbose_name='书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '每日推荐记录',
                'verbose_name_plural': '每日推荐记录',
                'unique_together': {('user', 'book', 'date')},
            },
        ),
    ]
