# Generated by Django 6.0.1 on 2026-04-08 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0020_bookrecolog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.CreateModel(
            name='BookGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='书单名称')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('books', models.ManyToManyField(blank=True, to='reader.book', verbose_name='书籍')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '书单',
                'verbose_name_plural': '书单',
                'ordering': ['-updated_at'],
            },
        ),
    ]
