# Generated by Django 6.0.1 on 2026-04-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0022_book_rating_avg_book_rating_count_bookrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='平均评分'),
        ),
    ]
